separator_color="magenta"
key_color="magenta"
prefer_small_ascii = true

[palette]
type="Dark"
visible=true

[box]
title="jdzialo"
border="double"
visible=true

[bar]
glyph="▮"
hide_delimiters=true
visible=true

[randomize]
key_color=false
separator_color=false

[custom_ascii]
color = "white"
path = "~/.config/macchina/themes/bonsai.txt"

[keys]
